### ISSUE TITLE
Create list of keywords to filter social media data

### ISSUE THREAD

**Issue by bermud** [bermud/geohealth-social#11]
Some terms can help us determine if a social media post is related to opioids or not.

- opioids
- narcan
- overdose
- #opiodcrisis

**Comment by nchavez1** [comment]
Additional (or maybe replacement) keywords to better target opioid users:
-recovery
-formerAddict
-Relapse 
-opiates
-suboxone
-methadone
-hydromorphone
-dilaudid

**Comment by bermud** [comment]
Sarah mentioned today

Alt search strings: (need OR want OR needing OR wanting)
 (too many OR two OR three OR double OR too much OR overdose OR crash OR strong enough OR max OR too many)
 (enough OR pop OR popping OR not enough OR another OR popped)
 (buy OR sell OR trade OR share OR spend OR bring OR steal)
Slang terms: (Oxys OR OxyCotton OR oxy OR roxies OR roxys OR oxycotin OR lortab OR tabbers OR Hydros OR Perc OR Percs OR Ercs OR Greenies OR dillies OR painkiller OR painkillers OR pain killer OR pain killers OR pain pills OR pain pill OR smack OR dope OR skag)

**Comment by bermud** [comment]
@HSRInc Ajay you said you might look at this and give us feedback on other possible searches?

**Comment by nchavez1** [comment]
Additional key words we are using:

- opiod
- safeInjectionSites
- dependency

**Comment by HSRInc** [comment]
I've shared the list with my LE friends and it looks good so far.  I like that you have identified a number of street slang for drugs. Looking forward to seeing what we come up with.
