### ISSUE TITLE
Analytics: decide what language library to use

### ISSUE THREAD

**Issue by snew-lib** [bermud/geohealth-social#13]

**Comment by snew-lib** [comment]
Some options:
- Spatial Hadoop (http://spatialhadoop.cs.umn.edu/)
- R Spatial (http://www.rspatial.org/)
- GeoPandas (http://geopandas.org/)

**Comment by snew-lib** [comment]
Tali, do you have a preference here?  I'm leaning towards GeoPandas, but we've used SpatialHadoop before, so maybe that's a safer choice.  We need to pick one so the server guys can get it installed!

**Comment by nchavez1** [comment]
My name is Nephtali :)

But is there a reason why you don't want to do python? I am suggesting python because I am most familiar with that language and we used it for the twitter API in our midterm.

**Comment by snew-lib** [comment]
Geopandas is a geospatial library for Python.  I think all we did with Python for the midterm was parse json data - not manipulate it.

**Comment by nchavez1** [comment]
And then we would create dump the results of python into GeoJSON which would go into leaflet. I think that is being discussed in issue 14. 

Are you thinking of having GeoPandas be the language we use exclusively?

**Comment by snew-lib** [comment]
I think we're going to need GeoPandas to create the shapes/layers that will be displayed in leaflet (based on tweet count or whatever measure the client wants).  So if we're doing intensity bubbles, I don't know how to create those in Python without a library.  Have you done something like that?

**Comment by snew-lib** [comment]
No, GeoPandas would be used in conjunction with Python

**Comment by nchavez1** [comment]
I think we should use hadoop because we have some experience with that. And we can also reach out for help from the class/professor if we are using hadoop vs some other unfamiliar language.

**Comment by snew-lib** [comment]
Ok, sounds good!
