### ISSUE TITLE
load external GeoJSON file into leaflet JavaScript

### ISSUE THREAD

**Issue by tigerdolphins** [bermud/geohealth-social#14]
I am having trouble loading GeoJSON from an external file into the HTML document containing the Leaflet Javascript code. Does anyone have good code from Homework 6(?) or the midterm which they can share with me for this project so I can adapt it for the team's use? My own code from those assignments was a mess that stored all the JSON data in various ways inside my script, and that is a terrible idea for this larger project.

**Comment by snew-lib** [comment]
Attaching mine here - let me know if anything doesn't make sense!


[midtermNew.zip](https://github.com/bermud/geohealth-social/files/1983799/midtermNew.zip)
