### ISSUE TITLE
Obtain other data sources

### ISSUE THREAD

**Issue by snew-lib** [bermud/geohealth-social#5]
Drug deliveries? Police data? EMS data? Hospital admissions?

**Comment by snew-lib** [comment]
CDC has some data, but it's old: https://www.cdc.gov/drugoverdose/maps/rxrate-maps.html

**Comment by bermud** [comment]
@Ajay, do you have available current opioid prescription that we can use?

**Comment by nchavez1** [comment]
@ajay mentioned PDMP data https://crisphealth.org/services/prescription-drug-monitoring-program-pdmp/
and HCUP data https://www.hcup-us.ahrq.gov/db/nation/nis/nisdbdocumentation.jsp, but I don't see any data for download on these sites. If this information can be obtained by the end of this week, maybe we can overlay it.

**Comment by snew-lib** [comment]
Thinking about other social media platforms, Yik Yak might be a possibility.  Every post is lat/long tagged and it's anonymous, so people might feel safe talking about drug use.  Not sure if there's an API available though.
