### ISSUE TITLE
Parse twitter data  filtering based on location and keywords

### ISSUE THREAD

**Issue by snew-lib** [bermud/geohealth-social#9]
Maryland

#opioidcrisis
opioid
Narcan
overdose

**Comment by snew-lib** [comment]
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets

**Comment by nchavez1** [comment]
I found this nice user interface for querying tweets, it doesn't seem like there are a super high number of tweets related to opioid use https://twitter.com/search-advanced

**Comment by nchavez1** [comment]
Also according to this page: https://developer.twitter.com/en/docs/tweets/search/overview the standard search AP for twitter only gives results from the last 7 days.
This issue might also be the same as issue #1

**Comment by snew-lib** [comment]
You're right!  Looks like we may need Premium access

**Comment by snew-lib** [comment]
Keyword sets I mentioned on our call:
Alt search strings: (need OR want OR needing OR wanting)
	(too many OR two OR three OR double OR too much OR overdose OR crash OR strong enough OR max OR too many)
	(enough OR pop OR popping OR not enough OR another OR popped)
	(buy OR sell OR trade OR share OR spend OR bring OR steal)

Slang terms: (Oxys OR OxyCotton OR oxy OR roxies OR roxys OR oxycotin OR lortab OR tabbers OR Hydros OR Perc OR Percs OR Ercs OR Greenies OR dillies OR painkiller OR painkillers OR pain killer OR pain killers OR pain pills OR pain pill OR smack OR dope OR skag)
